# -*- coding: utf-8 -*-

API_URLS = {
    'sandbox': 'https://connect.squareupsandbox.com',
    'production': 'https://connect.squareup.com',
}

# Square API version header (stable enough for Terminal + Refunds).
SQUARE_VERSION = '2024-10-17'

CHECKOUT_STATUS_COMPLETED = 'COMPLETED'
CHECKOUT_STATUS_CANCELED = 'CANCELED'
CHECKOUT_STATUS_CANCEL_REQUESTED = 'CANCEL_REQUESTED'
CHECKOUT_STATUS_PENDING = 'PENDING'
CHECKOUT_STATUS_IN_PROGRESS = 'IN_PROGRESS'

TERMINAL_SUCCESS_STATUSES = frozenset({CHECKOUT_STATUS_COMPLETED})
TERMINAL_FAILURE_STATUSES = frozenset({
    CHECKOUT_STATUS_CANCELED,
    CHECKOUT_STATUS_CANCEL_REQUESTED,
})
TERMINAL_PENDING_STATUSES = frozenset({
    CHECKOUT_STATUS_PENDING,
    CHECKOUT_STATUS_IN_PROGRESS,
})

REFUND_STATUS_COMPLETED = 'COMPLETED'
REFUND_STATUS_PENDING = 'PENDING'
REFUND_STATUS_FAILED = 'FAILED'
REFUND_STATUS_REJECTED = 'REJECTED'
